import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'

const poppins = Poppins({ subsets: ['latin'], weight: "500" })

export const metadata = {
  title: 'URLR',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${poppins.className} text-white`}>

        <Navbar />

        {children}

      </body>

    </html>
  )
}
