import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import useProfile from './utils/useProfile'

const poppins = Poppins({ subsets: ['latin'], weight: "500" })

export const metadata = {
  title: 'URLR',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  const profile = useProfile()
  
  return (
    <html lang="en">

      <body className={`${poppins.className}`}>

        <Navbar profile={profile} />

        {children}

      </body>

    </html>
  )
}
